```{r,echo=FALSE}
setwd("./")
```

```{r,echo=FALSE}
library(knitr)
knitr::opts_chunk$set(
    fig.align='center',external=TRUE, warning=FALSE, # alligns figures to center, no print warnings
    fig.pos='H', table.placement='H',  # makes tables and graphs in correct order with text
    fig.height=4, fig.width=6,
    echo=FALSE, message=FALSE, cache=FALSE, #don't print code or messages, saves in cache
    warn.conflicts=F,  # don't print warnings 
    tidy=TRUE,tidy.opts=list(width.cutoff=60)) # makes printing code not run off page
                a4width<- 8.3
                a4height<- 9
```


```{r}
load("train_results_for_standalone_noDx.rda") # training set of n=1011

#library(GrafGen) # don't need because training set file already provided
library(shiny)
library(ggplot2)
library(plotly)
library(dplyr)
library(scales)
library(RColorBrewer)
library(stringr)
library(cowplot)
library(ggpubr)

train_results_clean = train_results %>%
   mutate(label1 = paste0(Country,", ",Sample),
          label2 = paste0(Refpop,", ",Nearest_neighbor, ", ",round(Separation_percent,0),"%"),
          label3 = paste0(round(F_percent,0),
                          "%, ",round(E_percent,0),
                          "%, ",round(A_percent,0),"%")) %>%
   rename("Country, Sample"=label1,
          "Refpop, Neighbor, Separation"=label2,
          "African, European, Asian Ancestry"=label3)

# calculate frequency
refpop_n = train_results_clean %>%
   group_by(Refpop) %>%
   reframe(n=n()) %>%
   mutate(Refpop_n = paste0(gsub("hpgp","",Refpop),"\n","n=",n)) %>%
   select(-n)

refpop_order = train_results_clean %>%
   left_join(refpop_n,by="Refpop") %>%
   arrange(GD1_x) %>%
   mutate(Refpop_n=factor(Refpop_n,levels=unique(Refpop_n)))


train_results_clean = train_results_clean %>%
   left_join(refpop_n,by="Refpop") %>%
   mutate(Refpop_n=factor(Refpop_n,levels=levels(refpop_order$Refpop_n)),
          Refpop=factor(Refpop,levels=unique(refpop_order$Refpop)))


nb.cols <- 9
mycolors_fill <- colorRampPalette(brewer.pal(9, "Set1"))(nb.cols)

# Define the number of colors you want. 9 groups, 9 colors
nb.cols <- 60
mycolors <- colorRampPalette(brewer.pal(60, "Set1"))(nb.cols)



train_results_filtered = train_results_clean # apply no filters


p1 = ggplot(train_results_clean, aes(GD1_x, GD2_y))+
                         # theme stuff
                         theme_classic()+
                         theme(panel.background = element_blank(), panel.border = element_rect(fill = NA, color = "black"),
                               legend.title = element_blank(), legend.position="bottom", 
                               axis.text=element_text(face="bold",family="serif", color="black",size=15),
                               axis.title = element_text(face="bold",family="serif", color="black",size=15))+
                         guides(fill = guide_legend(nrow = 3), color=guide_legend(nrow=3))+
                         scale_fill_manual(values = mycolors_fill)+
                         scale_color_manual(values = mycolors)+
                         scale_x_continuous("GD1",breaks=pretty_breaks(n=10), limits=c(1,1.8))+
                         scale_y_continuous("GD2",breaks=pretty_breaks(n=10), limits=c(1,1.4))+
                         # ellipse of training data
                         stat_ellipse(aes(fill=Refpop_n, label4=Refpop),geom = "polygon",alpha=0.25)+
                         # make triangle
                         geom_segment(x = 1.05, y = 1.1, xend = 1.7658, yend = 1.1)+
                         geom_segment(x = 1.05, y = 1.1, xend = 1.4701, yend = 1.2897)+
                         geom_segment(x = 1.4701, y = 1.2897, xend = 1.7658, yend = 1.1)+
                         # data points
                         geom_point(data=train_results_filtered, 
                                    aes(label1=.data[["Country, Sample"]],
                                        label2=.data[["Refpop, Neighbor, Separation"]],
                                        label3=.data[["African, European, Asian Ancestry"]],
                                        color=Country.code),size=0.7)

```


```{r,fig.width=10.5,fig.height=10.5}
output =ggplotly(p1, tooltip=c("label1"="Country, Sample",
                               "label2"="Refpop, Neighbor, Separation",
                               "label3"="African, European, Asian Ancestry",
                               "label4"="Refpop")) %>%
   layout(legend = list(orientation = "h",y = -0.15)) %>%
           config(showTips = F) 

output$x$layout$legend$title$text="" # remove legend title
output$x$layout$legend$font$size=12 # change legend font size

#i=1
for(i in 1:length(output$x$data)){
   #output$x$data[[i]]$visible = "legendonly" # turns off all points by default
   
   #fix legend names
   if (!is.null(output$x$data[[i]]$name)){ output$x$data[[i]]$name =  gsub("\\(","",str_split(output$x$data[[i]]$name,",")[[1]][1]) }
   
   # adds spaces for hover variables
   if (!is.null(output$x$data[[i]]$text)){ output$x$data[[i]]$text = gsub("_"," ",output$x$data[[i]]$text) }
}

# for ellipses, change hover info to remove sample size
for(i in 1:(length(unique(train_results_clean$Refpop))+3)){
   output$x$data[[i]]$showlegend = FALSE # remove legends for points
   output$x$data[[i]]$legendgroup=NULL # keeps ellipse legends always on
   #output$x$data[[i]]$visible = "legendonly"
   output$x$data[[i]]$visible =TRUE 
}
output
```


```{r,fig.width=10.5,fig.height=0.5}
mylegend = ggplot(train_results_clean, aes(GD1_x,GD2_y))+
   geom_point(aes(fill=Refpop_n),shape=22,size=3, alpha=0.5)+
   theme_nothing()+
   theme(legend.position="top", legend.title = element_blank(),legend.text = element_text(size=12, family="serif"))+
   scale_fill_manual(values = mycolors_fill)+
   guides(fill = guide_legend(nrow = 1))

mylegend <- as_ggplot(get_legend(mylegend))
mylegend
```

